os:
  - linux
  - osx
language: node_js
node_js:
  - node
  - lts/*
jobs:
  allow_failures:
    - node_js: '6'
    - node_js: '4'
    - node_js: '0.12'
    - node_js: '0.10'

cache:
  yarn: true

before_install:
  - export PATH="$(yarn global bin):$PATH"
  - yarn add typescript ts-node

install:
  - yarn
  -

before_script:
  -
